import { defineField, defineType } from 'sanity'

export const ycfPageSingleton = defineType({
  name: 'ycfPage',
  title: 'Young Constructors Forum (YCF) Page',
  type: 'document',
  fields: [
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      options: { collapsible: true, collapsed: true },
    }),
    defineField({
      name: 'hero',
      title: 'Hero Section',
      type: 'hero',
      options: { collapsible: true, collapsed: true },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'pageBuilderSections',
      title: 'Page Builder Sections',
      type: 'array',
      of: [
        { type: 'featuresSection' },
        { type: 'contentSection' },
        { type: 'imageContent' },
        { type: 'imageCarouselContent' },
        { type: 'videoSection' },
        { type: 'splitImagesSection' },
        { type: 'awardSection' },
        { type: 'resourceLinksSection' },
        { type: 'splitContentSection' },
        { type: 'teamSectionByRole' },
        { type: 'servicesSection' },
        { type: 'newsSection' },
        { type: 'formSection' },
        { type: 'committeesSection' },
        { type: 'tabsSection' },
        { type: 'tabsTestimonialSection' },
        { type: 'ctaBand' },
        { type: 'carouselSection' },
        { type: 'testimonialsSection' },
        { type: 'photoGalleriesSection' },
        { type: 'embedPanelsSection' },
        { type: 'faqSection' },
        { type: 'sponsorLogosSection' },
      ],
    }),
  ],
  preview: {
    prepare: () => ({ title: 'Young Constructors Forum (YCF)' }),
  },
})
