import { committeeRedirects, legacy } from './legacy-redirect-helpers'

export const legacyRedirects = [
  { source: '/wp-content/:path*', destination: '/', permanent: true },
  { source: '/wp-admin/:path*', destination: '/', permanent: true },
  { source: '/wp-content/themes/:path*', destination: '/', permanent: true },
  { source: '/wp-content/plugins/:path*', destination: '/', permanent: true },
  { source: '/wp-content/uploads/:path*', destination: '/', permanent: true },
  { source: '/uploads/:path*', destination: '/', permanent: true },
  { source: '/scripts/:path*', destination: '/', permanent: true },
  { source: '/fmadmin/:path*', destination: '/', permanent: true },
  { source: '/feed', destination: '/', permanent: true },
  { source: '/feed/', destination: '/', permanent: true },
  { source: '/index.php', destination: '/', permanent: true },
  { source: '/index2.html', destination: '/', permanent: true },
  { source: '/committees.asp', destination: '/about/committees', permanent: true },
  { source: '/home', destination: '/', permanent: true },
  { source: '/calendar', destination: '/events/events-calendar', permanent: true },
  { source: '/sept03', destination: '/', permanent: true },
  { source: '/education-', destination: '/education-training', permanent: true },
  { source: '/events/events-', destination: '/events/events-calendar', permanent: true },
  { source: '/\\$', destination: '/', permanent: true },
  { source: '/&', destination: '/', permanent: true },
  { source: '/2023/:path*', destination: '/', permanent: true },
  { source: '/2022/:path*', destination: '/', permanent: true },
  { source: '/1969/:path*', destination: '/', permanent: true },
  { source: '/article/:path*', destination: '/news-media', permanent: true },
  { source: '/azagc-news/:path*', destination: '/news-media', permanent: true },
  { source: '/blog/:path*', destination: '/news-media', permanent: true },
  { source: '/industry-topics/:path*', destination: '/industry-resources', permanent: true },
  { source: '/news-media/category/:path*', destination: '/news-media', permanent: true },
  { source: '/news-media/author/:path*', destination: '/news-media', permanent: true },
  { source: '/category/:slug', destination: '/news-media', permanent: true },
  { source: '/tag/:slug', destination: '/news-media', permanent: true },
  { source: '/author/:slug', destination: '/about/our-team', permanent: true },
  ...legacy('/news-media/2', '/news-media?page=2'),
  ...legacy('/news-media/3', '/news-media?page=3'),
  ...legacy('/news-media/4', '/news-media?page=4'),
  ...legacy('/news-media/5', '/news-media?page=5'),
  { source: '/education-and-training/:path*', destination: '/education-training', permanent: true },
  {
    source: '/education-training/pavement-preservation-guidelines-documents/:path*',
    destination: '/education-training',
    permanent: true,
  },
  {
    source: '/membership/membership-directory',
    destination: '/membership/member-directory',
    permanent: true,
  },
  {
    source: '/membership/membership-directory/:path*',
    destination: '/membership/member-directory',
    permanent: true,
  },
  {
    source: '/membership-directory/:slug',
    destination: '/membership/member-directory',
    permanent: true,
  },
  {
    source: '/events/membership/member-directory',
    destination: '/membership/member-directory',
    permanent: true,
  },
  {
    source: '/resources/membership/member-directory',
    destination: '/membership/member-directory',
    permanent: true,
  },
  {
    source: '/membership/membership/member-directory',
    destination: '/membership/member-directory',
    permanent: true,
  },
  {
    source: '/lp/membership/member-directory',
    destination: '/lp/membership',
    permanent: true,
  },
  { source: '/advocacy/voter-tools/elected-officials/', destination: '/advocacy', permanent: true },
  { source: '/advocacy/key-commerce-corridors/:path*', destination: '/advocacy', permanent: true },
  {
    source: '/advocacy/government-affairs-voter-tools/:path*',
    destination: '/advocacy',
    permanent: true,
  },
  { source: '/advocacy/azagc-pac/:path*', destination: '/advocacy', permanent: true },
  { source: '/advocacy/legislative-update/:path*', destination: '/advocacy', permanent: true },
  { source: '/advocacy/governmental-affairs/:path*', destination: '/advocacy', permanent: true },
  {
    source: '/events/events-calendar/details',
    destination: '/events/events-calendar',
    permanent: true,
  },
  {
    source: '/events/events-calendar/details/:path*',
    destination: '/events/events-calendar',
    permanent: true,
  },
  { source: '/about/industry-partnerships/:path*', destination: '/about', permanent: true },
  { source: '/about/about/:path*', destination: '/about', permanent: true },
  {
    source: '/about/2019-az-transportation-partnering-excellence-awards-booklet/:path*',
    destination: '/about',
    permanent: true,
  },
  ...committeeRedirects,
  ...legacy('/about-us', '/about'),
  ...legacy('/blog', '/news-media'),
  ...legacy('/education', '/education-training'),
  ...legacy('/news-and-media', '/news-media'),
  ...legacy('/ycf', '/membership/ycf'),
  ...legacy('/strategic-planning', '/strategicplanning'),
  ...legacy('/membership/membership-dues', '/membership/dues'),
  ...legacy('/studio', '/'),
  ...legacy('/mc-template', '/'),
  {
    source: '/uploads/sites/1/Lovas_Phil.pdf',
    destination: '/',
    permanent: true,
  },
  {
    source:
      '/2023/09/22/manufacturing-transportation-gains-lift-construction-starts',
    destination: '/',
    permanent: true,
  },
  ...legacy(
    '/industry-topics/workforce-development',
    '/education-training/workforce-development-programs',
  ),
  ...legacy('/news-media/welcome-new-member-march', '/news-media'),
  ...legacy(
    '/news-media/pinal-county-proposes-new-micro‑trenching-standards-what-it-means-for-arizona-contractors',
    '/news-media',
  ),
]
